version: '3.3'

services:
  whoami:
    image: "traefik/whoami"
    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.whoami.rule=Host(`whoami.kamptos.com`)"
        - "traefik.http.routers.whoami.entrypoints=http"
        - "traefik.http.services.whoami.loadbalancer.server.port=80"
        - "traefik.http.routers.whoami-secured.rule=Host(`whoami.kamptos.com`)"
        - "traefik.http.routers.whoami-secured.entrypoints=https"
        - "traefik.http.routers.whoami-secured.tls.certresolver=mytlschallenge"
        - traefik.docker.network=traefik-public
        - traefik.constraint-label=traefik-public
    networks:
      - traefik-public
        
networks:
  # Use the previously created public network "traefik-public", shared with other
  # services that need to be publicly available via this Traefik
  traefik-public:
    external: true
